export const mockMarketplace = [
    { id: "M-001", name: "all-skills-from-skills-sh", desc: "来源于 skills.sh 网站，通过抓取获得的所有 skill", type: "文本", category: "大模型", technicalDomain: ["知识蒸馏", "能力评估"], industryDomain: ["互联网和相关服务", "软件和信息技术服务业"], tasks: ["文本分类", "关系抽取", "语义理解", "词分类"], size: "16 GB", tags: ["检索增强", "逻辑推理", "Apache 2.0"], isOfficial: true, applyCount: 516, updatedAt: "2026-02-28", version: "v2.1.0", creator: "超级大只老咪" },
    { id: "M-002", name: "YodaLingua-preview", desc: "YodaLingua 是一个高质量的语音数据集，专为训练文本转语音 (TTS) 系统...", type: "文本", category: "大模型", technicalDomain: ["语音识别", "多模态"], industryDomain: ["广播、电视、电影和录音制作业"], tasks: ["语音识别", "语音合成", "互联网"], size: "6 GB", tags: ["多语言", "语音合成", "Apache 2.0"], isOfficial: true, applyCount: 61, updatedAt: "2026-02-27", version: "v1.0.5", creator: "超级大只老咪" },
    { id: "M-003", name: "Cybersecurity-Dataset", desc: "首个由新加坡幻域网络科技有限公司开源的超大规模网络安全数据集 整合全网...", type: "图像", category: "模型能力评估", technicalDomain: ["逻辑推理", "对齐人类偏好"], industryDomain: ["软件和信息技术服务业"], tasks: ["能力评估", "互联网"], size: "2 GB", tags: ["安全", "互联网", "Apache 2.0"], isOfficial: true, applyCount: 78, updatedAt: "2026-02-27", version: "v1.0.0", creator: "超级大只老咪" },
    { id: "M-004", name: "delicate medical r1 data", desc: "基于华伦开源的高质量医疗语料库", type: "文本", category: "模型能力评估", technicalDomain: ["强化学习", "提示词工程"], industryDomain: ["卫生"], tasks: ["微调", "医疗"], size: "12 GB", tags: ["医疗", "问答", "Apache 2.0"], isOfficial: true, applyCount: 48, updatedAt: "2026-02-26", version: "v3.0.0", creator: "超级大只老咪" },
    { id: "M-005", name: "SA1B-Dense-Caption", desc: "长文本图文描述", type: "图像", category: "计算机视觉", technicalDomain: ["多模态", "图像超分辨率"], industryDomain: ["科技推广和应用服务业"], tasks: ["多模态", "科技", "互联网"], size: "6 GB", tags: ["图文", "描述", "Apache 2.0"], isOfficial: true, applyCount: 46, updatedAt: "2026-02-26", version: "v1.2.0", creator: "超级大只老咪" },
    { id: "M-006", name: "SKYLENAGE-ReasoningMATH", desc: "覆盖从基础算术到高等数学的多层次推理任务，涵盖逻辑推导、代数变换、...", type: "文本", category: "计算机视觉", technicalDomain: ["逻辑推理", "综合测试"], industryDomain: ["教育"], tasks: ["微调", "能力评估", "检索增强", "逻辑推理"], size: "7 GB", tags: ["数学", "推理", "Apache 2.0"], isOfficial: true, applyCount: 37, updatedAt: "2026-02-26", version: "v2.0.0", creator: "超级大只老咪" },
    { id: "M-007", name: "rag-bench-public-questions", desc: "rag-bench-public-questions", type: "文本", category: "大模型", technicalDomain: ["检索增强", "知识问答"], industryDomain: ["互联网和相关服务"], tasks: ["能力评估", "检索增强"], size: "41 GB", tags: ["RAG", "问答"], isOfficial: false, applyCount: 2300, updatedAt: "2026-01-06", creator: "coffee_dou(为PPDE努力版)" },
    { id: "M-008", name: "hermes-function-calling-v1-all", desc: "hermes-function-calling-v1-all", type: "文本", category: "大模型", technicalDomain: ["智能体", "编程代码"], industryDomain: ["互联网和相关服务"], tasks: ["逻辑推理", "智能体"], size: "14 GB", tags: ["Function Call", "Agent"], isOfficial: false, applyCount: 159, updatedAt: "2026-01-07", creator: "皮都坦率的法夏" },
];
